import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@rainbow-me/rainbowkit/styles.css";
import {Rainbowkit} from "./providers"
import Header from "./Header"
import Sidebar from "./Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export interface NavLink {
  name: string
  href: string
}
const links: NavLink[] = [
  {
    name: "Docs",
    href: "/",
  },
  {
    name: "Components",
    href: "/",
  },
  {
    name: "Blog",
    href: "/",
  }
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Rainbowkit>
          <Header links={links} />
          <div className="flex h-full relative">
            <Sidebar links={links} />
            <div className="w-full px-6 lg:px-8 bg-blue-100">
              {children}
            </div>
          </div>
        </Rainbowkit>
      </body>
    </html>
  );
}

